FROM public.ecr.aws/lambda/python:3.10

COPY ./backend ${LAMBDA_TASK_ROOT}

# COPY .//requirements.txt ./requirements.txt

# RUN pip install psycopg2-binary
# RUN apk add postgresql-dev gcc python3-dev musl-dev

RUN yum install -y gcc python3-devel postgresql-devel

# RUN pipx install poetry
# RUN poetry install
RUN pip install psycopg2-binary

RUN pip3 install -r ${LAMBDA_TASK_ROOT}/requirements.txt --target "${LAMBDA_TASK_ROOT}"

CMD ["app.handler"]
