name: "Build & upload vue app to S3"
on:
  push:
    branches:
      - dev
    # - main
  pull_request:

jobs:
  s3-deploy:
    name: "Build and Upload to S3"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Get yarn cache directory path 🛠
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node_modules 📦
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: |
          cd frontend
          yarn --frozen-lockfile

      - name: Build dependencies 🛠
        env:
          AWS_EXPORTS: ${{ secrets.AMPLIFY_AWS_EXPORTS }}
        run: |
          cd frontend
          echo $AWS_EXPORTS > aws-exports.js
          yarn build

      # - name: Build application
      #   run: |
      #     cd frontend
      #     yarn install
      #     yarn run build

      - name: Deploying application to Amazon S3
        env:
          AWS_BUCKET_NAME: ${{ secrets.AWS_FRONTEND_BUCKET_NAME }}
        run: |
          cd frontend
          aws s3 sync ./dist s3://$AWS_BUCKET_NAME --delete

        # uses: dvelasquez/deploy-s3-action@main
        # with:
        #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #   AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        #   AWS_BUCKET_NAME: ${{ secrets.AWS_FRONTEND_BUCKET_NAME }}
        #   BUCKET_PATH: ${{ secrets.AWS_DEFAULT_REGION }} # Or to upload a pull_request: "/pr/${{github.event.number}}"
        #   DIST_LOCATION_CODE: ./frontend/dist
